### ISSUE TITLE
Use swap files instead of swap partitions

### ISSUE THREAD

**Issue by fraenki** [opnsense/bsdinstaller#9]
Apparently, swap files are superior to traditional swap partitions in many ways. I suggest to change the installer to create swap files instead of swap partitions for the default/easy installation. (An experienced user would still be able to configure swap partitions, if desired.)

Benefits:
- swap file can easily be destroyed if the user needs disk space (disk filling up)
- swap space can easily be increased or decreased if required by the user

If you agree to this proposal, I'll try to make the required changes and provide a PR (ETA Q2/2018).

**Comment by fichtner** [comment]
We can already create 2GB swap file from the system misc page. It‘s optional, mainly for systems with <1GB with small storage or nanobsd that would otherwise not have swap at all. It can be extended, the value it writes during save is „2“, creating a backwards-compatible behaviour if the swap usage was to be extended.

The downside of swap files is critical: we cannot store kernel crash reports on those systems without a swap partition.

For that reason, I would like to retain the behaviour of using a swap partition, and optionally configuring a (larger) (additional) swap file if needed.

**Comment by fraenki** [comment]
> The downside of swap files is critical: we cannot store kernel crash reports on those systems without a swap partition.

What a pity! I wasn't aware of this. Seems like nobody is working on this limitation right now, so I'm closing this issue...
